/* generate a matrix for octave -
 * use "sort -n" to get points in order, and add a header
 */

#include <stdio.h>
#include <stdint.h>

#define DATBITS 128
#define PARBITS (DATBITS * 2)	/* 1/3 code rate */
#define DEPTH 2
#define PRIMES {13,47};

int16_t cols[DATBITS][DEPTH * 2];

void fillcols(uint16_t row, uint16_t col) {
	int i;

	for (i = 0; i < 2 * DEPTH; i++) {
		if (!cols[col][i]) {
			cols[col][i] = row + 1;
			return;
		}
	}
	printf("%s","Failed !\n");
	return;
}

int main(void) {
	int b,d,i;
	int16_t prime[DEPTH] = PRIMES;

	printf("%s","\n// Autogenerated by prime numbers:\n//\t");
	for (b=0; b < DEPTH; b++)
		printf("%d;",prime[b]);

	printf("%s","\n\n");

	for (d=0; d < DEPTH; d++) {
		for (b=0; b < PARBITS; b++) {
			uint16_t offset;

			offset = (3 * (b * prime[d] + d)) % DATBITS;
			printf("%03d %03d 1\n", b+1, offset+1);
		}
	}
	return 0;
}

